name: flutter_vimeo
description: "Flutter package to play Vimeo videos using the InAppWebView plugin."
version: 1.0.8
repository: https://github.com/NijatNaghiyev/flutter_vimeo

environment:
  sdk: ^3.7.2
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5


flutter:
